### PR TITLE
fix live mode today push notification

### LINKED ISSUE #471: looks like "live_mode_today" push was broken
https://sentry.io/organizations/since-kindly/issues/2884812184/?environment=prod&project=5972006&referrer=alert_email

### PR DESCRIPTION
**Pull request by ruslandoga**
closes #471

### CODE REVIEW

**Comment by ruslandoga** [comment]
@akhrail1996 I can schedule this job to run now if needed.

File: dev/dev.ex [hunk 1]
```diff
@@ -1,4 +1,10 @@
 defmodule Dev do
+  def notify_live_mode_today do
+    Oban.insert!(
+      T.PushNotifications.DispatchJob.new(%{"type" => "live_mode_today", "time" => "20:00"})
+    )
+  end
```
Comment (ruslandoga) [inline dev/dev.ex:6]: Or you can do it yourself.
