### PR TITLE
fix n+1 db calls in views

### LINKED ISSUE #480: remove db calls from views
https://github.com/getsince/test3/blob/c938e8ae9200cac79c518822e310e92411379ab7/lib/t_web/views/match_view.ex#L10

### PR DESCRIPTION
**Pull request by ruslandoga**
closes #480

### CODE REVIEW

File: lib/t/matches.ex [hunk 1]
```diff
@@ -1055,23 +1062,27 @@ defmodule T.Matches do
...
+  def match_soon_to_expire_check(reference \\ DateTime.utc_now()) do
+    day_before_expiration = reference |> DateTime.add(-@match_ttl) |> DateTime.add(24 * 3600)
+    day_and_one_minute_before_expiration = DateTime.add(day_before_expiration, 60)
+
     expiring_matches_q()
-    |> where([m, e, c], e.timestamp <= fragment("now() - interval '6 days'"))
-    |> where([m, e, c], e.timestamp > fragment("now() - interval '6 days 1 minute'"))
-    |> select([m, e, c], m.id)
+    |> where([m], m.inserted_at <= ^day_before_expiration)
+    # TODO can result in duplicates with more than one worker
```
Comment (ruslandoga) [inline lib/t/matches.ex:1083]: - [ ] create issue

File: test/t_web/channels/feed_channel_test.exs [hunk 2]
```diff
@@ -72,17 +72,18 @@ defmodule TWeb.FeedChannelTest do
...
                %{
                  "id" => m2.id,
                  "profile" => %{name: "mate-2", story: [], user_id: p2.id, gender: "N"},
-                 "contact" => %{
-                   "contacts" => %{"whatsapp" => "+79666666666"},
-                   "picker" => p2.id,
-                   "opened_contact_type" => nil
+                 "timeslot" => %{
+                   "picker" => me.id,
+                   "slots" => slots
```
Comment (ruslandoga) [inline test/t_web/channels/feed_channel_test.exs:83]: @akhrail1996 it appears that this test was wrong, according to [the comment above](https://github.com/getsince/test3/blob/c938e8ae9200cac79c518822e310e92411379ab7/test/t_web/channels/feed_channel_test.exs#L60)

File: test/t_web/channels/feed_channel_test.exs [hunk 3]
```diff
@@ -72,17 +72,18 @@ defmodule TWeb.FeedChannelTest do
                  "id" => m3.id,
                  "profile" => %{name: "mate-3", story: [], user_id: p3.id, gender: "M"},
                  "timeslot" => %{"selected_slot" => s2},
-                 "audio_only" => false
+                 "audio_only" => false,
+                 "expiration_date" => ~U[2021-10-07 12:16:07Z]
```
Comment (ruslandoga) [inline test/t_web/channels/feed_channel_test.exs:76]: @akhrail1996 since the matches didn't have started calls and reported meetings, `expiration_date` should be returned

File: lib/t/matches.ex [hunk 4]
```diff
@@ -302,20 +314,37 @@ defmodule T.Matches do
...
+    |> Enum.map(fn {match, timeslot, contact, undying_event_timestamp} ->
+      expiration_date =
+        unless undying_event_timestamp do
+          expiration_date(match)
+        end
+
+      %Match{
+        match
+        | timeslot: timeslot,
+          contact: contact,
```
Comment (akhrail1996) [inline lib/t/matches.ex:334]: does %Match{} need `timeslot` & `contact` when it has interaction?

**Comment by ruslandoga** [comment]
@akhrail1996 I didn't understand why some of the matches without calls and meeting reports didn't include `expiration_date` in feed channel payloads, was it a mistake or by design?

File: lib/t/matches.ex (hunk 1 above)
Comment (ruslandoga) [reply lib/t/matches.ex:1105]: moved to https://github.com/getsince/test3/issues/482

File: test/t_web/channels/feed_channel_test.exs [hunk 5]
```diff
@@ -72,17 +72,18 @@ defmodule TWeb.FeedChannelTest do
...
                },
                %{
                  "id" => m2.id,
                  "profile" => %{name: "mate-2", story: [], user_id: p2.id, gender: "N"},
-                 "contact" => %{
-                   "contacts" => %{"whatsapp" => "+79666666666"},
-                   "picker" => p2.id,
-                   "opened_contact_type" => nil
+                 "timeslot" => %{
```
Comment (akhrail1996) [inline test/t_web/channels/feed_channel_test.exs:81]: > # add contact to m2, but it won't be returned since there is a timeslot as well
(from https://github.com/getsince/test3/pull/481/files#diff-ecf0850f17c63f59b2690d88d79fbd691819ed852ee56937771756ddd24c19c8L60) is incorrect, I undestand now why you were confused  - I forgot to delete this comment when making some of the changes (sorry for this 🙏)

so actually "whatsapp" contact should be returned here

Comment (akhrail1996) [reply test/t_web/channels/feed_channel_test.exs:81]: since contact was shared later than timeslot -> was supposed to overwrite it

**Review by akhrail1996 — CHANGES_REQUESTED** [review]

File: test/t_web/channels/feed_channel_test.exs (hunk 2 above)
Comment (akhrail1996) [reply test/t_web/channels/feed_channel_test.exs:83]: @ruslandoga actually it's the other way around - test is correct, but comment was wrong 🙃

File: lib/t/matches.ex (hunk 4 above)
Comment (ruslandoga) [reply lib/t/matches.ex:334]: why not?

File: test/t_web/channels/feed_channel_test.exs (hunk 3 above)
Comment (akhrail1996) [reply test/t_web/channels/feed_channel_test.exs:76]: @ruslandoga yes, I don't remember why exactly it wasn't rendered here (though it didn't affect real usage) - but it should be

**Comment by akhrail1996** [comment]
> @akhrail1996 I didn't understand why some of the matches without calls and meeting reports didn't include `expiration_date` in feed channel payloads, was it a mistake or by design?

@ruslandoga yes, it was a mistake

File: lib/t/matches.ex (hunk 4 above)
Comment (akhrail1996) [reply lib/t/matches.ex:334]: no reason
rather wanted to understand rationale - maybe you had something in mind where they will be needed later or something.

File: test/t_web/channels/feed_channel_test.exs (hunk 5 above)
Comment (ruslandoga) [reply test/t_web/channels/feed_channel_test.exs:85]: I've updated the test and it's still wrong, the tests was successful before because of the order function clauses matched in the view.

File: lib/t/matches.ex [hunk 6]
```diff
@@ -302,20 +314,37 @@ defmodule T.Matches do
...
+          expiration_date: expiration_date,
+          interaction: timeslot || contact
```
Comment (ruslandoga) [inline lib/t/matches.ex:336]: @akhrail1996 the previous behaviour int he match_view is `contact || timeslot`

File: test/t_web/channels/feed_channel_test.exs (hunk 5 above)
Comment (akhrail1996) [reply test/t_web/channels/feed_channel_test.exs:85]: for some reason I thought that in this PR `interaction` is supposed (?) to determine the latest interaction mode => here the latest interaction mode would be `contact` then

nevertheless the current PR is probably safe to merge as well, since current client wouldn't allow for `timeslot` and `contact` to co-exist anyways (user would need to "cancel" contact / timeslot to send timeslot / contact)

so we can implement the above functionality (`interaction` being based on the latest interaction mode or rather one new interaction mode overriding content of the previous one -> guarantee of one interaction mode at a time for match) in a separate PR (probably in voicemail one)

Comment (akhrail1996) [reply test/t_web/channels/feed_channel_test.exs:85]: > since current client wouldn't allow for timeslot and contact to co-exist anyways (user would need to "cancel" contact / timeslot to send timeslot / contact)

but in the next version of the client I plan to remove this from client -> needs to be done in `voicemail` PR

**Review by akhrail1996 — APPROVED** [review]

File: test/t_web/channels/feed_channel_test.exs (hunk 5 above)
Comment (ruslandoga) [reply test/t_web/channels/feed_channel_test.exs:85]: > for some reason I thought that in this PR interaction is supposed

no,  this pr refactors match_view db calls which were to calculate expiration

Comment (ruslandoga) [reply test/t_web/channels/feed_channel_test.exs:85]: no, I don't think it makes sense to do in voicemail PR

Comment (ruslandoga) [reply test/t_web/channels/feed_channel_test.exs:85]: moved to https://github.com/getsince/test3/issues/483
